name: Release

on:
  workflow_dispatch:

env:
  CI: 1
  ARTIFACT_DIR: ./artifacts

jobs:
  release:
    name: Publish ESLint Import Resolver Plugin
    runs-on: ubuntu-20.04
    steps:
        - uses: actions/checkout@v2
          with:
            token: ${{ secrets.TOPHAT_BOT_GH_TOKEN }}
            fetch-depth: 0
        - uses: ./.github/actions/detect-env
        - name: Setup Node.js
          uses: actions/setup-node@v1
          with:
            node-version: ${{ env.NODE_VERSION }}
        - name: Create artifacts directory
          run: mkdir -p ${{ env.ARTIFACT_DIR }}
        - name: Restore yarn cache
          id: yarn-cache
          uses: actions/cache@v2
          with:
            path: |
              ./.yarn
              ./.pnp.*
            key: ${{ env.NODE_VERSION }}-${{ env.YARN_VERSION }}-${{ hashFiles('yarn.lock') }}
        - name: Install dependencies
          run: yarn install --immutable
        - name: Configure Git
          run: |
            git config --global user.name tophat-opensource-bot
            git config --global user.email opensource-leads+bot@tophatmonocle.com
            git config --global init.defaultBranch master
        - name: Publish via Monodeploy
          if: github.ref == 'refs/heads/master'
          env:
            NPM_PUBLISH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
          run: |
            yarn monodeploy --log-level 0 --config-file=monodeploy.config.js
        - name: Update Git Repository
          if: github.ref == 'refs/heads/master'
          run: |
            yarn dedupe
            if ! git diff-index --quiet HEAD -- CHANGELOG.md; then
              git push --tags \
                && git add yarn.lock CHANGELOG.md "package.json" \
                && git commit -m "chore: release eslint import resolver require [skip ci]" \
                && git push
            fi
        - name: Upload Artifacts
          if: ${{ always() }}
          uses: actions/upload-artifact@v2
          with:
            name: reports-and-build-artifacts
            path: |
                ${{ env.ARTIFACT_DIR }}
